# ===============================
# SERVER CONFIGURATION
# ===============================
spring.application.name=uniride-trips-service
server.port=8084

# ===============================
# DATABASE CONFIGURATION (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/uniride_db
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SECURITY CONFIGURATION (JWT)
# ===============================
jwt.secret=UniRide_2026_SecretKey_TripsSvc_9f8d7c6b5a4e3f2g1h0j9k8l7m6n5o4p3